name: Free macOS Remote Desktop (Stable)
on: workflow_dispatch

jobs:
  build:
   runs-on: macos-14
    steps:
    - name: Mac Me VNC Setup Karo
      run: |
        # Remote Screen Sharing Chalu Karne Ka Command
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -clientopts -setvnclegacy -vnclegacy yes -clientopts -setvncpw -vncpw MacOSFree123 -restart -agent -privs -all
        
        # Mac Ka Password Set/Reset Karna
        sudo dscl . -passwd /Users/runner MacOSFree123

    - name: Tunnel Banayein Aur Link Print Karein
      uses: mxschmitt/action-tmate@v3

