name: Free macOS Remote Desktop (No Card Required)
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Mac Me VNC Setup Karo
      run: |
        # Remote Screen Sharing Active Karne Ka Command
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -clientopts -setvnclegacy -vnclegacy yes -clientopts -setvncpw -vncpw MacOSFree123 -restart -agent -privs -all
        
        # Password Bypass Configuration
        echo "MacOSFree123" | sudo passwd --stdin runner || echo "MacOSFree123" | sudo passwd runner || true

    - name: Free Tunnel Chalu Karo
      uses: mxschmitt/action-tmate@v3


